# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Album(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, title: str=None, artist_id: int=None):  # noqa: E501
        """Album - a model defined in Swagger

        :param id: The id of this Album.  # noqa: E501
        :type id: int
        :param title: The title of this Album.  # noqa: E501
        :type title: str
        :param artist_id: The artist_id of this Album.  # noqa: E501
        :type artist_id: int
        """
        self.swagger_types = {
            'id': int,
            'title': str,
            'artist_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'Title',
            'artist_id': 'ArtistId'
        }
        self._id = id
        self._title = title
        self._artist_id = artist_id

    @classmethod
    def from_dict(cls, dikt) -> 'Album':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Album of this Album.  # noqa: E501
        :rtype: Album
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Album.


        :return: The id of this Album.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Album.


        :param id: The id of this Album.
        :type id: int
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Album.


        :return: The title of this Album.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Album.


        :param title: The title of this Album.
        :type title: str
        """

        self._title = title

    @property
    def artist_id(self) -> int:
        """Gets the artist_id of this Album.


        :return: The artist_id of this Album.
        :rtype: int
        """
        return self._artist_id

    @artist_id.setter
    def artist_id(self, artist_id: int):
        """Sets the artist_id of this Album.


        :param artist_id: The artist_id of this Album.
        :type artist_id: int
        """

        self._artist_id = artist_id
