# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class Customer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, last_name: str=None, first_name: str=None, company: str=None, address: str=None, city: str=None, state: str=None, country: str=None, zip_code: str=None, phone: str=None, email: str=None, support_rep_id: int=None):  # noqa: E501
        """Customer - a model defined in Swagger

        :param id: The id of this Customer.  # noqa: E501
        :type id: int
        :param last_name: The last_name of this Customer.  # noqa: E501
        :type last_name: str
        :param first_name: The first_name of this Customer.  # noqa: E501
        :type first_name: str
        :param company: The company of this Customer.  # noqa: E501
        :type company: str
        :param address: The address of this Customer.  # noqa: E501
        :type address: str
        :param city: The city of this Customer.  # noqa: E501
        :type city: str
        :param state: The state of this Customer.  # noqa: E501
        :type state: str
        :param country: The country of this Customer.  # noqa: E501
        :type country: str
        :param zip_code: The zip_code of this Customer.  # noqa: E501
        :type zip_code: str
        :param phone: The phone of this Customer.  # noqa: E501
        :type phone: str
        :param email: The email of this Customer.  # noqa: E501
        :type email: str
        :param support_rep_id: The support_rep_id of this Customer.  # noqa: E501
        :type support_rep_id: int
        """
        self.swagger_types = {
            'id': int,
            'last_name': str,
            'first_name': str,
            'company': str,
            'address': str,
            'city': str,
            'state': str,
            'country': str,
            'zip_code': str,
            'phone': str,
            'email': str,
            'support_rep_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'last_name': 'LastName',
            'first_name': 'FirstName',
            'company': 'Company',
            'address': 'Address',
            'city': 'City',
            'state': 'State',
            'country': 'Country',
            'zip_code': 'ZipCode',
            'phone': 'Phone',
            'email': 'Email',
            'support_rep_id': 'SupportRepId'
        }
        self._id = id
        self._last_name = last_name
        self._first_name = first_name
        self._company = company
        self._address = address
        self._city = city
        self._state = state
        self._country = country
        self._zip_code = zip_code
        self._phone = phone
        self._email = email
        self._support_rep_id = support_rep_id

    @classmethod
    def from_dict(cls, dikt) -> 'Customer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Customer of this Customer.  # noqa: E501
        :rtype: Customer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Customer.


        :return: The id of this Customer.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Customer.


        :param id: The id of this Customer.
        :type id: int
        """

        self._id = id

    @property
    def last_name(self) -> str:
        """Gets the last_name of this Customer.


        :return: The last_name of this Customer.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this Customer.


        :param last_name: The last_name of this Customer.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def first_name(self) -> str:
        """Gets the first_name of this Customer.


        :return: The first_name of this Customer.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this Customer.


        :param first_name: The first_name of this Customer.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def company(self) -> str:
        """Gets the company of this Customer.


        :return: The company of this Customer.
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company: str):
        """Sets the company of this Customer.


        :param company: The company of this Customer.
        :type company: str
        """

        self._company = company

    @property
    def address(self) -> str:
        """Gets the address of this Customer.


        :return: The address of this Customer.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this Customer.


        :param address: The address of this Customer.
        :type address: str
        """

        self._address = address

    @property
    def city(self) -> str:
        """Gets the city of this Customer.


        :return: The city of this Customer.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this Customer.


        :param city: The city of this Customer.
        :type city: str
        """

        self._city = city

    @property
    def state(self) -> str:
        """Gets the state of this Customer.


        :return: The state of this Customer.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this Customer.


        :param state: The state of this Customer.
        :type state: str
        """

        self._state = state

    @property
    def country(self) -> str:
        """Gets the country of this Customer.


        :return: The country of this Customer.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this Customer.


        :param country: The country of this Customer.
        :type country: str
        """

        self._country = country

    @property
    def zip_code(self) -> str:
        """Gets the zip_code of this Customer.


        :return: The zip_code of this Customer.
        :rtype: str
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code: str):
        """Sets the zip_code of this Customer.


        :param zip_code: The zip_code of this Customer.
        :type zip_code: str
        """

        self._zip_code = zip_code

    @property
    def phone(self) -> str:
        """Gets the phone of this Customer.


        :return: The phone of this Customer.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this Customer.


        :param phone: The phone of this Customer.
        :type phone: str
        """

        self._phone = phone

    @property
    def email(self) -> str:
        """Gets the email of this Customer.


        :return: The email of this Customer.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Customer.


        :param email: The email of this Customer.
        :type email: str
        """

        self._email = email

    @property
    def support_rep_id(self) -> int:
        """Gets the support_rep_id of this Customer.


        :return: The support_rep_id of this Customer.
        :rtype: int
        """
        return self._support_rep_id

    @support_rep_id.setter
    def support_rep_id(self, support_rep_id: int):
        """Sets the support_rep_id of this Customer.


        :param support_rep_id: The support_rep_id of this Customer.
        :type support_rep_id: int
        """

        self._support_rep_id = support_rep_id
