# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class Employee(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, last_name: str=None, first_name: str=None, title: str=None, reports_to: int=None, birth_date: date=None, hire_date: date=None, company: str=None, address: str=None, city: str=None, state: str=None, country: str=None, zip_code: str=None, phone: str=None, email: str=None):  # noqa: E501
        """Employee - a model defined in Swagger

        :param last_name: The last_name of this Employee.  # noqa: E501
        :type last_name: str
        :param first_name: The first_name of this Employee.  # noqa: E501
        :type first_name: str
        :param title: The title of this Employee.  # noqa: E501
        :type title: str
        :param reports_to: The reports_to of this Employee.  # noqa: E501
        :type reports_to: int
        :param birth_date: The birth_date of this Employee.  # noqa: E501
        :type birth_date: date
        :param hire_date: The hire_date of this Employee.  # noqa: E501
        :type hire_date: date
        :param company: The company of this Employee.  # noqa: E501
        :type company: str
        :param address: The address of this Employee.  # noqa: E501
        :type address: str
        :param city: The city of this Employee.  # noqa: E501
        :type city: str
        :param state: The state of this Employee.  # noqa: E501
        :type state: str
        :param country: The country of this Employee.  # noqa: E501
        :type country: str
        :param zip_code: The zip_code of this Employee.  # noqa: E501
        :type zip_code: str
        :param phone: The phone of this Employee.  # noqa: E501
        :type phone: str
        :param email: The email of this Employee.  # noqa: E501
        :type email: str
        """
        self.swagger_types = {
            'last_name': str,
            'first_name': str,
            'title': str,
            'reports_to': int,
            'birth_date': date,
            'hire_date': date,
            'company': str,
            'address': str,
            'city': str,
            'state': str,
            'country': str,
            'zip_code': str,
            'phone': str,
            'email': str
        }

        self.attribute_map = {
            'last_name': 'LastName',
            'first_name': 'FirstName',
            'title': 'Title',
            'reports_to': 'ReportsTo',
            'birth_date': 'BirthDate',
            'hire_date': 'HireDate',
            'company': 'Company',
            'address': 'Address',
            'city': 'City',
            'state': 'State',
            'country': 'Country',
            'zip_code': 'ZipCode',
            'phone': 'Phone',
            'email': 'Email'
        }
        self._last_name = last_name
        self._first_name = first_name
        self._title = title
        self._reports_to = reports_to
        self._birth_date = birth_date
        self._hire_date = hire_date
        self._company = company
        self._address = address
        self._city = city
        self._state = state
        self._country = country
        self._zip_code = zip_code
        self._phone = phone
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'Employee':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Employee of this Employee.  # noqa: E501
        :rtype: Employee
        """
        return util.deserialize_model(dikt, cls)

    @property
    def last_name(self) -> str:
        """Gets the last_name of this Employee.


        :return: The last_name of this Employee.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this Employee.


        :param last_name: The last_name of this Employee.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def first_name(self) -> str:
        """Gets the first_name of this Employee.


        :return: The first_name of this Employee.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this Employee.


        :param first_name: The first_name of this Employee.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def title(self) -> str:
        """Gets the title of this Employee.


        :return: The title of this Employee.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Employee.


        :param title: The title of this Employee.
        :type title: str
        """

        self._title = title

    @property
    def reports_to(self) -> int:
        """Gets the reports_to of this Employee.


        :return: The reports_to of this Employee.
        :rtype: int
        """
        return self._reports_to

    @reports_to.setter
    def reports_to(self, reports_to: int):
        """Sets the reports_to of this Employee.


        :param reports_to: The reports_to of this Employee.
        :type reports_to: int
        """

        self._reports_to = reports_to

    @property
    def birth_date(self) -> date:
        """Gets the birth_date of this Employee.


        :return: The birth_date of this Employee.
        :rtype: date
        """
        return self._birth_date

    @birth_date.setter
    def birth_date(self, birth_date: date):
        """Sets the birth_date of this Employee.


        :param birth_date: The birth_date of this Employee.
        :type birth_date: date
        """

        self._birth_date = birth_date

    @property
    def hire_date(self) -> date:
        """Gets the hire_date of this Employee.


        :return: The hire_date of this Employee.
        :rtype: date
        """
        return self._hire_date

    @hire_date.setter
    def hire_date(self, hire_date: date):
        """Sets the hire_date of this Employee.


        :param hire_date: The hire_date of this Employee.
        :type hire_date: date
        """

        self._hire_date = hire_date

    @property
    def company(self) -> str:
        """Gets the company of this Employee.


        :return: The company of this Employee.
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company: str):
        """Sets the company of this Employee.


        :param company: The company of this Employee.
        :type company: str
        """

        self._company = company

    @property
    def address(self) -> str:
        """Gets the address of this Employee.


        :return: The address of this Employee.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this Employee.


        :param address: The address of this Employee.
        :type address: str
        """

        self._address = address

    @property
    def city(self) -> str:
        """Gets the city of this Employee.


        :return: The city of this Employee.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this Employee.


        :param city: The city of this Employee.
        :type city: str
        """

        self._city = city

    @property
    def state(self) -> str:
        """Gets the state of this Employee.


        :return: The state of this Employee.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this Employee.


        :param state: The state of this Employee.
        :type state: str
        """

        self._state = state

    @property
    def country(self) -> str:
        """Gets the country of this Employee.


        :return: The country of this Employee.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this Employee.


        :param country: The country of this Employee.
        :type country: str
        """

        self._country = country

    @property
    def zip_code(self) -> str:
        """Gets the zip_code of this Employee.


        :return: The zip_code of this Employee.
        :rtype: str
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code: str):
        """Sets the zip_code of this Employee.


        :param zip_code: The zip_code of this Employee.
        :type zip_code: str
        """

        self._zip_code = zip_code

    @property
    def phone(self) -> str:
        """Gets the phone of this Employee.


        :return: The phone of this Employee.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this Employee.


        :param phone: The phone of this Employee.
        :type phone: str
        """

        self._phone = phone

    @property
    def email(self) -> str:
        """Gets the email of this Employee.


        :return: The email of this Employee.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Employee.


        :param email: The email of this Employee.
        :type email: str
        """

        self._email = email
