# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server.models.any_of_invoice_invoicelines_items import AnyOfInvoiceInvoicelinesItems  # noqa: F401,E501
from swagger_server import util


class Invoice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, customer_id: int=None, invoice_date: datetime=None, billing_address: str=None, billing_city: str=None, billing_state: str=None, billing_country: str=None, billing_zip_code: str=None, total: float=None, invoicelines: List[AnyOfInvoiceInvoicelinesItems]=None):  # noqa: E501
        """Invoice - a model defined in Swagger

        :param id: The id of this Invoice.  # noqa: E501
        :type id: int
        :param customer_id: The customer_id of this Invoice.  # noqa: E501
        :type customer_id: int
        :param invoice_date: The invoice_date of this Invoice.  # noqa: E501
        :type invoice_date: datetime
        :param billing_address: The billing_address of this Invoice.  # noqa: E501
        :type billing_address: str
        :param billing_city: The billing_city of this Invoice.  # noqa: E501
        :type billing_city: str
        :param billing_state: The billing_state of this Invoice.  # noqa: E501
        :type billing_state: str
        :param billing_country: The billing_country of this Invoice.  # noqa: E501
        :type billing_country: str
        :param billing_zip_code: The billing_zip_code of this Invoice.  # noqa: E501
        :type billing_zip_code: str
        :param total: The total of this Invoice.  # noqa: E501
        :type total: float
        :param invoicelines: The invoicelines of this Invoice.  # noqa: E501
        :type invoicelines: List[AnyOfInvoiceInvoicelinesItems]
        """
        self.swagger_types = {
            'id': int,
            'customer_id': int,
            'invoice_date': datetime,
            'billing_address': str,
            'billing_city': str,
            'billing_state': str,
            'billing_country': str,
            'billing_zip_code': str,
            'total': float,
            'invoicelines': List[AnyOfInvoiceInvoicelinesItems]
        }

        self.attribute_map = {
            'id': 'id',
            'customer_id': 'CustomerId',
            'invoice_date': 'InvoiceDate',
            'billing_address': 'BillingAddress',
            'billing_city': 'BillingCity',
            'billing_state': 'BillingState',
            'billing_country': 'BillingCountry',
            'billing_zip_code': 'BillingZipCode',
            'total': 'Total',
            'invoicelines': 'invoicelines'
        }
        self._id = id
        self._customer_id = customer_id
        self._invoice_date = invoice_date
        self._billing_address = billing_address
        self._billing_city = billing_city
        self._billing_state = billing_state
        self._billing_country = billing_country
        self._billing_zip_code = billing_zip_code
        self._total = total
        self._invoicelines = invoicelines

    @classmethod
    def from_dict(cls, dikt) -> 'Invoice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Invoice of this Invoice.  # noqa: E501
        :rtype: Invoice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Invoice.


        :return: The id of this Invoice.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Invoice.


        :param id: The id of this Invoice.
        :type id: int
        """

        self._id = id

    @property
    def customer_id(self) -> int:
        """Gets the customer_id of this Invoice.


        :return: The customer_id of this Invoice.
        :rtype: int
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id: int):
        """Sets the customer_id of this Invoice.


        :param customer_id: The customer_id of this Invoice.
        :type customer_id: int
        """

        self._customer_id = customer_id

    @property
    def invoice_date(self) -> datetime:
        """Gets the invoice_date of this Invoice.


        :return: The invoice_date of this Invoice.
        :rtype: datetime
        """
        return self._invoice_date

    @invoice_date.setter
    def invoice_date(self, invoice_date: datetime):
        """Sets the invoice_date of this Invoice.


        :param invoice_date: The invoice_date of this Invoice.
        :type invoice_date: datetime
        """

        self._invoice_date = invoice_date

    @property
    def billing_address(self) -> str:
        """Gets the billing_address of this Invoice.


        :return: The billing_address of this Invoice.
        :rtype: str
        """
        return self._billing_address

    @billing_address.setter
    def billing_address(self, billing_address: str):
        """Sets the billing_address of this Invoice.


        :param billing_address: The billing_address of this Invoice.
        :type billing_address: str
        """

        self._billing_address = billing_address

    @property
    def billing_city(self) -> str:
        """Gets the billing_city of this Invoice.


        :return: The billing_city of this Invoice.
        :rtype: str
        """
        return self._billing_city

    @billing_city.setter
    def billing_city(self, billing_city: str):
        """Sets the billing_city of this Invoice.


        :param billing_city: The billing_city of this Invoice.
        :type billing_city: str
        """

        self._billing_city = billing_city

    @property
    def billing_state(self) -> str:
        """Gets the billing_state of this Invoice.


        :return: The billing_state of this Invoice.
        :rtype: str
        """
        return self._billing_state

    @billing_state.setter
    def billing_state(self, billing_state: str):
        """Sets the billing_state of this Invoice.


        :param billing_state: The billing_state of this Invoice.
        :type billing_state: str
        """

        self._billing_state = billing_state

    @property
    def billing_country(self) -> str:
        """Gets the billing_country of this Invoice.


        :return: The billing_country of this Invoice.
        :rtype: str
        """
        return self._billing_country

    @billing_country.setter
    def billing_country(self, billing_country: str):
        """Sets the billing_country of this Invoice.


        :param billing_country: The billing_country of this Invoice.
        :type billing_country: str
        """

        self._billing_country = billing_country

    @property
    def billing_zip_code(self) -> str:
        """Gets the billing_zip_code of this Invoice.


        :return: The billing_zip_code of this Invoice.
        :rtype: str
        """
        return self._billing_zip_code

    @billing_zip_code.setter
    def billing_zip_code(self, billing_zip_code: str):
        """Sets the billing_zip_code of this Invoice.


        :param billing_zip_code: The billing_zip_code of this Invoice.
        :type billing_zip_code: str
        """

        self._billing_zip_code = billing_zip_code

    @property
    def total(self) -> float:
        """Gets the total of this Invoice.


        :return: The total of this Invoice.
        :rtype: float
        """
        return self._total

    @total.setter
    def total(self, total: float):
        """Sets the total of this Invoice.


        :param total: The total of this Invoice.
        :type total: float
        """

        self._total = total

    @property
    def invoicelines(self) -> List[AnyOfInvoiceInvoicelinesItems]:
        """Gets the invoicelines of this Invoice.


        :return: The invoicelines of this Invoice.
        :rtype: List[AnyOfInvoiceInvoicelinesItems]
        """
        return self._invoicelines

    @invoicelines.setter
    def invoicelines(self, invoicelines: List[AnyOfInvoiceInvoicelinesItems]):
        """Sets the invoicelines of this Invoice.


        :param invoicelines: The invoicelines of this Invoice.
        :type invoicelines: List[AnyOfInvoiceInvoicelinesItems]
        """

        self._invoicelines = invoicelines
