# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InvoiceLine(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, invoice_id: int=None, track_id: int=None, unit_price: float=None, quantity: int=None):  # noqa: E501
        """InvoiceLine - a model defined in Swagger

        :param id: The id of this InvoiceLine.  # noqa: E501
        :type id: int
        :param invoice_id: The invoice_id of this InvoiceLine.  # noqa: E501
        :type invoice_id: int
        :param track_id: The track_id of this InvoiceLine.  # noqa: E501
        :type track_id: int
        :param unit_price: The unit_price of this InvoiceLine.  # noqa: E501
        :type unit_price: float
        :param quantity: The quantity of this InvoiceLine.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'id': int,
            'invoice_id': int,
            'track_id': int,
            'unit_price': float,
            'quantity': int
        }

        self.attribute_map = {
            'id': 'id',
            'invoice_id': 'InvoiceId',
            'track_id': 'TrackId',
            'unit_price': 'UnitPrice',
            'quantity': 'Quantity'
        }
        self._id = id
        self._invoice_id = invoice_id
        self._track_id = track_id
        self._unit_price = unit_price
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'InvoiceLine':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InvoiceLine of this InvoiceLine.  # noqa: E501
        :rtype: InvoiceLine
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this InvoiceLine.


        :return: The id of this InvoiceLine.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InvoiceLine.


        :param id: The id of this InvoiceLine.
        :type id: int
        """

        self._id = id

    @property
    def invoice_id(self) -> int:
        """Gets the invoice_id of this InvoiceLine.


        :return: The invoice_id of this InvoiceLine.
        :rtype: int
        """
        return self._invoice_id

    @invoice_id.setter
    def invoice_id(self, invoice_id: int):
        """Sets the invoice_id of this InvoiceLine.


        :param invoice_id: The invoice_id of this InvoiceLine.
        :type invoice_id: int
        """

        self._invoice_id = invoice_id

    @property
    def track_id(self) -> int:
        """Gets the track_id of this InvoiceLine.


        :return: The track_id of this InvoiceLine.
        :rtype: int
        """
        return self._track_id

    @track_id.setter
    def track_id(self, track_id: int):
        """Sets the track_id of this InvoiceLine.


        :param track_id: The track_id of this InvoiceLine.
        :type track_id: int
        """

        self._track_id = track_id

    @property
    def unit_price(self) -> float:
        """Gets the unit_price of this InvoiceLine.


        :return: The unit_price of this InvoiceLine.
        :rtype: float
        """
        return self._unit_price

    @unit_price.setter
    def unit_price(self, unit_price: float):
        """Sets the unit_price of this InvoiceLine.


        :param unit_price: The unit_price of this InvoiceLine.
        :type unit_price: float
        """

        self._unit_price = unit_price

    @property
    def quantity(self) -> int:
        """Gets the quantity of this InvoiceLine.


        :return: The quantity of this InvoiceLine.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this InvoiceLine.


        :param quantity: The quantity of this InvoiceLine.
        :type quantity: int
        """

        self._quantity = quantity
