# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.any_of_playlist_tracks_items import AnyOfPlaylistTracksItems  # noqa: F401,E501
from swagger_server import util


class Playlist(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, tracks: List[AnyOfPlaylistTracksItems]=None):  # noqa: E501
        """Playlist - a model defined in Swagger

        :param id: The id of this Playlist.  # noqa: E501
        :type id: int
        :param name: The name of this Playlist.  # noqa: E501
        :type name: str
        :param tracks: The tracks of this Playlist.  # noqa: E501
        :type tracks: List[AnyOfPlaylistTracksItems]
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'tracks': List[AnyOfPlaylistTracksItems]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'Name',
            'tracks': 'tracks'
        }
        self._id = id
        self._name = name
        self._tracks = tracks

    @classmethod
    def from_dict(cls, dikt) -> 'Playlist':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Playlist of this Playlist.  # noqa: E501
        :rtype: Playlist
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Playlist.


        :return: The id of this Playlist.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Playlist.


        :param id: The id of this Playlist.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Playlist.


        :return: The name of this Playlist.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Playlist.


        :param name: The name of this Playlist.
        :type name: str
        """

        self._name = name

    @property
    def tracks(self) -> List[AnyOfPlaylistTracksItems]:
        """Gets the tracks of this Playlist.


        :return: The tracks of this Playlist.
        :rtype: List[AnyOfPlaylistTracksItems]
        """
        return self._tracks

    @tracks.setter
    def tracks(self, tracks: List[AnyOfPlaylistTracksItems]):
        """Sets the tracks of this Playlist.


        :param tracks: The tracks of this Playlist.
        :type tracks: List[AnyOfPlaylistTracksItems]
        """

        self._tracks = tracks
