# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PlaylistTrack(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, playlist_id: int=None, track_id: int=None):  # noqa: E501
        """PlaylistTrack - a model defined in Swagger

        :param id: The id of this PlaylistTrack.  # noqa: E501
        :type id: int
        :param playlist_id: The playlist_id of this PlaylistTrack.  # noqa: E501
        :type playlist_id: int
        :param track_id: The track_id of this PlaylistTrack.  # noqa: E501
        :type track_id: int
        """
        self.swagger_types = {
            'id': int,
            'playlist_id': int,
            'track_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'playlist_id': 'PlaylistId',
            'track_id': 'TrackId'
        }
        self._id = id
        self._playlist_id = playlist_id
        self._track_id = track_id

    @classmethod
    def from_dict(cls, dikt) -> 'PlaylistTrack':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlaylistTrack of this PlaylistTrack.  # noqa: E501
        :rtype: PlaylistTrack
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this PlaylistTrack.


        :return: The id of this PlaylistTrack.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this PlaylistTrack.


        :param id: The id of this PlaylistTrack.
        :type id: int
        """

        self._id = id

    @property
    def playlist_id(self) -> int:
        """Gets the playlist_id of this PlaylistTrack.


        :return: The playlist_id of this PlaylistTrack.
        :rtype: int
        """
        return self._playlist_id

    @playlist_id.setter
    def playlist_id(self, playlist_id: int):
        """Sets the playlist_id of this PlaylistTrack.


        :param playlist_id: The playlist_id of this PlaylistTrack.
        :type playlist_id: int
        """

        self._playlist_id = playlist_id

    @property
    def track_id(self) -> int:
        """Gets the track_id of this PlaylistTrack.


        :return: The track_id of this PlaylistTrack.
        :rtype: int
        """
        return self._track_id

    @track_id.setter
    def track_id(self, track_id: int):
        """Sets the track_id of this PlaylistTrack.


        :param track_id: The track_id of this PlaylistTrack.
        :type track_id: int
        """

        self._track_id = track_id
