# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Track(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, album_id: int=None, media_type_id: int=None, genre_id: int=None, composer: str=None, milliseconds: int=None, bytes: int=None, unit_price: float=None):  # noqa: E501
        """Track - a model defined in Swagger

        :param id: The id of this Track.  # noqa: E501
        :type id: int
        :param name: The name of this Track.  # noqa: E501
        :type name: str
        :param album_id: The album_id of this Track.  # noqa: E501
        :type album_id: int
        :param media_type_id: The media_type_id of this Track.  # noqa: E501
        :type media_type_id: int
        :param genre_id: The genre_id of this Track.  # noqa: E501
        :type genre_id: int
        :param composer: The composer of this Track.  # noqa: E501
        :type composer: str
        :param milliseconds: The milliseconds of this Track.  # noqa: E501
        :type milliseconds: int
        :param bytes: The bytes of this Track.  # noqa: E501
        :type bytes: int
        :param unit_price: The unit_price of this Track.  # noqa: E501
        :type unit_price: float
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'album_id': int,
            'media_type_id': int,
            'genre_id': int,
            'composer': str,
            'milliseconds': int,
            'bytes': int,
            'unit_price': float
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'Name',
            'album_id': 'AlbumId',
            'media_type_id': 'MediaTypeId',
            'genre_id': 'GenreId',
            'composer': 'Composer',
            'milliseconds': 'Milliseconds',
            'bytes': 'Bytes',
            'unit_price': 'UnitPrice'
        }
        self._id = id
        self._name = name
        self._album_id = album_id
        self._media_type_id = media_type_id
        self._genre_id = genre_id
        self._composer = composer
        self._milliseconds = milliseconds
        self._bytes = bytes
        self._unit_price = unit_price

    @classmethod
    def from_dict(cls, dikt) -> 'Track':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Track of this Track.  # noqa: E501
        :rtype: Track
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Track.


        :return: The id of this Track.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Track.


        :param id: The id of this Track.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Track.


        :return: The name of this Track.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Track.


        :param name: The name of this Track.
        :type name: str
        """

        self._name = name

    @property
    def album_id(self) -> int:
        """Gets the album_id of this Track.


        :return: The album_id of this Track.
        :rtype: int
        """
        return self._album_id

    @album_id.setter
    def album_id(self, album_id: int):
        """Sets the album_id of this Track.


        :param album_id: The album_id of this Track.
        :type album_id: int
        """

        self._album_id = album_id

    @property
    def media_type_id(self) -> int:
        """Gets the media_type_id of this Track.


        :return: The media_type_id of this Track.
        :rtype: int
        """
        return self._media_type_id

    @media_type_id.setter
    def media_type_id(self, media_type_id: int):
        """Sets the media_type_id of this Track.


        :param media_type_id: The media_type_id of this Track.
        :type media_type_id: int
        """

        self._media_type_id = media_type_id

    @property
    def genre_id(self) -> int:
        """Gets the genre_id of this Track.


        :return: The genre_id of this Track.
        :rtype: int
        """
        return self._genre_id

    @genre_id.setter
    def genre_id(self, genre_id: int):
        """Sets the genre_id of this Track.


        :param genre_id: The genre_id of this Track.
        :type genre_id: int
        """

        self._genre_id = genre_id

    @property
    def composer(self) -> str:
        """Gets the composer of this Track.


        :return: The composer of this Track.
        :rtype: str
        """
        return self._composer

    @composer.setter
    def composer(self, composer: str):
        """Sets the composer of this Track.


        :param composer: The composer of this Track.
        :type composer: str
        """

        self._composer = composer

    @property
    def milliseconds(self) -> int:
        """Gets the milliseconds of this Track.


        :return: The milliseconds of this Track.
        :rtype: int
        """
        return self._milliseconds

    @milliseconds.setter
    def milliseconds(self, milliseconds: int):
        """Sets the milliseconds of this Track.


        :param milliseconds: The milliseconds of this Track.
        :type milliseconds: int
        """

        self._milliseconds = milliseconds

    @property
    def bytes(self) -> int:
        """Gets the bytes of this Track.


        :return: The bytes of this Track.
        :rtype: int
        """
        return self._bytes

    @bytes.setter
    def bytes(self, bytes: int):
        """Sets the bytes of this Track.


        :param bytes: The bytes of this Track.
        :type bytes: int
        """

        self._bytes = bytes

    @property
    def unit_price(self) -> float:
        """Gets the unit_price of this Track.


        :return: The unit_price of this Track.
        :rtype: float
        """
        return self._unit_price

    @unit_price.setter
    def unit_price(self, unit_price: float):
        """Sets the unit_price of this Track.


        :param unit_price: The unit_price of this Track.
        :type unit_price: float
        """

        self._unit_price = unit_price
